export const packageName = '@cashcount/db' as const;

export { createDatabaseClient, type DatabaseClient } from './client.js';
export { defaultMigrationsFolder, runMigrations } from './migrations.js';
export { seedSyntheticIdentity, syntheticIdentitySeed } from './seed.js';
export {
  financialRoles,
  TransactionNotFoundError,
  TransactionUserStateConflictError,
  TransactionUserStateRepository,
  transactionReviewStatuses,
  type EffectiveTransactionUserState,
  type FinancialRole,
  type NullableOverridePatch,
  type OverridePatch,
  type TransactionReviewStatus,
  type TransactionUserStateRecord,
  type UpdateTransactionUserStateInput,
  type UserStateActorType,
} from './transaction-user-state-repository.js';
export {
  appUser,
  auditEvent,
  billPaymentReconciliation,
  category,
  classificationDecision,
  classificationRule,
  creditCardBill,
  creditCardBillFinanceCharge,
  creditCardBillPayment,
  financialAccount,
  financialTransaction,
  installmentSeries,
  jobQueue,
  merchant,
  merchantAlias,
  providerConnection,
  providerRawObject,
  reconciliationCurrencyTolerance,
  recurringSeries,
  syncRun,
  tag,
  transactionIdentityLink,
  transactionRevision,
  transactionTag,
  transactionUserState,
  webhookEvent,
  workspace,
  workspaceMember,
} from './schema.js';
