export const packageName = '@cashcount/classification' as const;

export {
  descriptionNormalizationPolicyVersion,
  normalizeTransactionDescription,
  type DescriptionNormalizationResult,
  type InstallmentDescriptionMetadata,
  type LocationOrStoreSuffix,
  type PaymentProcessorPrefix,
  type TransactionReference,
  type TransactionReferenceKind,
} from './description-normalizer.js';
export {
  merchantCandidateSimilarity,
  merchantFuzzyReviewThreshold,
  merchantPatternAutoMatchThreshold,
  merchantResolutionPolicyVersion,
} from './merchant-similarity.js';
export {
  classificationRuleActionsSchema,
  classificationRuleActionTypes,
  classificationRuleConditionsSchema,
  classificationRuleDslSchema,
  classificationRuleDslVersion,
  classificationRuleFields,
  classificationRuleMaxActions,
  classificationRuleMaxConditionsPerGroup,
  classificationRuleMaxDepth,
  classificationRuleMaxDocumentBytes,
  classificationRuleMaxInValues,
  classificationRuleMaxNodes,
  classificationRuleMaxPatternLength,
  classificationRuleMaxRegexInputLength,
  classificationRuleOperators,
  compileSafeRulePattern,
  parseClassificationRuleDsl,
  testSafeRulePattern,
  type ClassificationRuleAction,
  type ClassificationRuleActions,
  type ClassificationRuleConditionGroup,
  type ClassificationRuleConditionNode,
  type ClassificationRuleConditions,
  type ClassificationRuleDsl,
  type ClassificationRuleField,
  type ClassificationRuleOperator,
  type ClassificationRulePredicate,
} from './rule-dsl.js';
